=== SamPerCap/FileManager/FileManager/XMLFiles/ComputerSchemaExtended.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="Computer">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Brand" type="xs:string" minOccurs="1"/>
        <xs:element name="Color" type="colorType"/>
        <xs:element name="Price" type="priceType" minOccurs="1"/>
        <xs:element name="ReleaseYear" type="xs:date"/>
        <xs:element name="FactoryInfo" type="FactoryInfo"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- OUR DEFINED TYPES-->
  <xs:simpleType name="priceType">
    <xs:restriction base="xs:double">
      <xs:minExclusive value="0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="colorType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Red" />
      <xs:enumeration value="Orange" />
      <xs:enumeration value="Yellow" />
      <xs:enumeration value="Green" />
      <xs:enumeration value="Blue" />
      <xs:enumeration value="Purple" />
      <xs:enumeration value="Brown" />
      <xs:enumeration value="Magenta" />
      <xs:enumeration value="Black" />
      <xs:enumeration value="Grey" />
      <xs:enumeration value="White" />
      <xs:enumeration value="Pink" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="CountryInfo">
    <xs:sequence>
      <xs:element name ="CountryName" type="xs:string"/>
      <xs:element name ="Continent" type="xs:string"/>
      <xs:element name ="Hemisphere" type="Hemisphere"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="Hemisphere">
    <xs:restriction base="xs:string">
      <xs:enumeration value ="North"/>
      <xs:enumeration value ="South"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name ="FactoryInfo">
    <xs:sequence>
      <xs:element name="CountryInfo" type="CountryInfo"/>
      <xs:element name="FactoryName" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== SamPerCap/FileManager/FileManager/XMLFiles/ComputerExtended.xml
<?xml version="1.0" encoding="utf-8"?>

<Computer
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="ComputerSchemaExtended.xsd">
  <Brand>HP</Brand>
  <Color>Grey</Color>
  <Price>3</Price>
  <ReleaseYear>2012-12-13</ReleaseYear>
  <FactoryInfo>
    <CountryInfo>
      <CountryName>Denmark</CountryName>
      <Continent>Europe</Continent>
      <Hemisphere>North</Hemisphere>
    </CountryInfo>
    <FactoryName>HPFactory</FactoryName>
  </FactoryInfo>
</Computer>
